### ISSUE TITLE
Error can't compile - could not find the package

### ISSUE THREAD

**Issue by shaeon** [EremusOne/ZX-ESPectrum-IDF#19]
Hello, 
 
 I was trying compile pico32 and when tried download dependencies it was giving me an error:

`Tool Manager: Installing espressif/toolchain-riscv32-esp @↓ 8.4.0+2021r2-patch2
Error: Could not find package with 'espressif/toolchain-riscv32-esp @ 8.4.0.+2021r2-patch2' requirements for your system 'windows_amd64'`

@rampa069 give support and adding in platformio.ini file after [env] next lines fix my error and can finish and play with ZX-ESPectrum-IDF:

`[env]
platform_packages =
    toolchain-riscv32-esp @ 8.4.0+2021r2-patch5`

I open this Issues to help others can compile without error.

Best Regards and great job!

**Comment by EremusOne** [comment]
Thx for posting the issue shaeon. We'll test this in a clean install of dev tools and repo and will add the line to platformio.ini file if needed.

Enjoy the emu! ;)

**Comment by nix256** [comment]
![2023-06-14](https://github.com/EremusOne/ZX-ESPectrum-IDF/assets/32455782/2c77ff0d-cc50-4596-88dd-d3a45892438f)
не получается.

**Comment by nix256** [comment]
windows 11 x64 16Gb памяти.

**Comment by nix256** [comment]
![2023-06-14 (1)](https://github.com/EremusOne/ZX-ESPectrum-IDF/assets/32455782/ed2fb42a-44f9-4bab-ba2b-373a3bee6f4b)
прошил. нет запуска. ttgo v_1.4

**Comment by nix256** [comment]
![20230614_230238](https://github.com/EremusOne/ZX-ESPectrum-IDF/assets/32455782/7c482bea-8aa4-4e1a-9f67-5374ab74d9e2)
помогите откомпилировать и пришлите на почту пожалуйста.nix256@yandex.ru

**Comment by EremusOne** [comment]
Hi nix256,

I can help you in my spare time but you have to help me to help you taking these points in consideration:

1. Before asking for help, post detailed instructions on which things have you tried and the steps you've done.
2. Don't flood the issue with different posts. You can edit posts.
3. Ask for help in english please.

That said, add a carriage return to that line:

[env]
platform_packages = toolchain-riscv32-esp @ 8.4.0+2021r2-patch5

and try again.

Regards

**Comment by nix256** [comment]
yes, I suffered a week of zero effect. sit and press the keys to switch to the VGA keyboard erased. it's bad when they spread it and it doesn't work for people.
