### ISSUE TITLE
Acts as if the down arrow key is pressed.

### ISSUE THREAD

**Issue by m1zar** [EremusOne/ZX-ESPectrum-IDF#20]
Hi, just flashed the latest version, rc1 and it's behaving as though the down arrow key is being pressed in all menus. Not sure why that would be the case. I'm using a PS/2 keyboard (IBM Model M), which was fine with the previous beta. What happens is I press F1 to get the menu, the menu appears, there's a short (typmatic repeat delay?) and it starts going down the menu list by itself. And just goes round and round. Tried removing the keyboard (to see if that made a diff, after hitting F1 to get the menu) and it just loops around. Can 'catch' menu items with enter/return, and the sub menus show the same issue, looping around. Interestingly if I actually press the down arrow key, it speeds up and slows down when I release the key, so it's not a stuck key issue, seems to be something with the keyboard routine. The Snapshot list, it runs to the end and then stops (don't think that menu loops). Anyway, love the emulator, keep up the good work. Think this is by far the best ESP32VGA spectrum emulator available, if not the best standalone emulator period.

https://github.com/EremusOne/ZX-ESPectrum-IDF/assets/24475126/c8369650-2fcf-48a9-a9f2-1c8b21ce66ba

**Comment by m1zar** [comment]
Oh, should add I'm using the ESP32VGA 1.4 module. Used the ESPtool to flash the new .bin file, and that's it.

**Comment by m1zar** [comment]
Apologies, think this is my error, I flashed the new board version not the ESP32VGA board version. RTFM as they say!

**Comment by EremusOne** [comment]
Hi m1zar,

I see you found the source of your issue. I have made the same mistake more than once during development.

Thx anyway for opening the issue, it can be helpful to other people.

Enjoy the emu! ;)

**Comment by m1zar** [comment]
Hi Victor,

  Yes, it was indeed the wrong version and is now working perfectly, thank
you. Thanks for all your hard work on the emulator, it's great to be able
to have the full experience with the tape loading etc.
  I'm looking foreword to TZX support in the future. I also have a
suggestion, that the ZX81 could also be emulated, as it shouldn't require
much additional code (Similar Keyboard/Same CPU), and would expand the
appeal of the emulator, and there's quite an alive community around the
ZX81 Hi-Res games, including manic miner etc. Amazing and it would be
awesome to be able to play those on the emulator as well. But it's only an
idea, and probably doesn't compare in any way to the following for the
spectrum side of things, and I already love where it's at. I also like the
idea of being able to save code from basic would be super, as I do like to
write the odd bit here and there and it would be great to be able to save
it. (Guess I can already with snapshots... but to files would be great.)
  On snapshots, at present we can snapshot to one of a small number of
slots, in the future it would be nice to be able to save to named snapshot
files, as when I load tape image files, it would be great to be able to
save them to a named snapshot file, to save making one externally in
another emulator.
  I do love how the screen sizes have been done, with the proper thick
border and the sound is now awesome also, and much appreciated as is the
Volume Control, brilliant.

Thanks and all my thanks, it's a really awesome piece of work.

Cheers,
James
(M1ZAR)

**Comment by EremusOne** [comment]
Thanks for all your kind comments and suggestions James.

Right now we're focusing on showing the emu to the world and getting feedback (as yours ;) ).

Anyway, we have an internal roadmap and when, more soon than later, we return to code you'll see implemented some of the things you've mentioned (Can't give you ETA's right now sorry).

Regards
