### ISSUE TITLE
Sub folders needed in parent folders to organize collections

### ISSUE THREAD

**Issue by Magnetrix** [EremusOne/ZX-ESPectrum-IDF#21]
Please can you enable use of sub-folders on "t","c","s","p" to reorganize collections of files?
Thanks

**Comment by EremusOne** [comment]
Hi,

Subfolders are something we have planned in the roadmap. I can't give you a date but it's very likely that they will be available soon.

Thanks for your interest in our emulator ;)

**Comment by EremusOne** [comment]
Hi,

Subfolders are something we have planned in the roadmap. I can't give you a date but it's very likely that they will be available soon.

Thanks for your interest in our emulator ;)
