### ISSUE TITLE
Show full snapshot/tape names

### ISSUE THREAD

**Issue by SanPollo** [EremusOne/ZX-ESPectrum-IDF#22]
When browsing from SNA/Z80 snapshots, or TAP files to load, files with longer names are truncated to 8+3.

Please make the **Select Snapshot** and **Select TAP** windows the width of the screen so that all filenames are fully visible.

**Comment by EremusOne** [comment]
Yes, if I remember well, names longer than 24+3 are truncated to 8+3.

This is done for three reasons: keep memory consumption low, keep coherence between SPIFFS and SD filesystems and need of having a functional version of filebrowser ASAP.

Anyway, here's the answer you've came here for: yes, it will change in the future and filenames will show more characters.

When? In the future when we have the time or soon if u fancy to code it ;)

Regards and thanks for using our emu!

**Comment by EremusOne** [comment]
Closing as answered
