### ISSUE TITLE
ESPectrum 1.0 rc1 on ESP32-SBC-FabGL no image

### ISSUE THREAD

**Issue by Magnetrix** [EremusOne/ZX-ESPectrum-IDF#23]
Hello, 
I flashed this board from olimex with your rc1 bin file, as I did on TTGo VGA32, but I have no display on my VGA monitor with this Olimex Board...
Maybe there is a fix, but I am not a programmer and I don't know how to compile form source code files.
If someone can help I will be gratful
Thank you

**Comment by Magnetrix** [comment]
Erase and flash again solve my issue... Now is working :)

**Comment by EremusOne** [comment]
Nice to know, enjoy the emu ;)

We'll gonna test also in that board soon, looks interesting.

BTW: Could you send us a picture of the emu running on the board for publishing it on our website? Thanks in advance
