### ISSUE TITLE
ESPectrum 1.0 rc1 on ESP32-SBC-FabGL SD card issue

### ISSUE THREAD

**Issue by Magnetrix** [EremusOne/ZX-ESPectrum-IDF#24]
Hello,
When i select external Sd as my storage option, and press F5, no games list is presented.
This card when inserted om my other board TTGo vga32 works great.
Anyone can help me?
Regards

**Comment by EremusOne** [comment]
It seems Olimex has used different pins for the SD card slot:

You'll have to change this line in hardpins.h:

#define PIN_NUM_MISO GPIO_NUM_2

to:

#define PIN_NUM_MISO GPIO_NUM_35

Unfortunately, I've no Olimex board to test it so you'll have to compile and test it for yourself. Let me know if this solves it.

Regards!

**Comment by Magnetrix** [comment]
I am not a programmer, so I don't have skills to know how compile the code. The internal speaker of the board doesn't output sound... sound only outputs from jack 3.5mm... 
![ESP32-SBC-FabGL_ZX-ESPectrum-IDF](https://github.com/EremusOne/ZX-ESPectrum-IDF/assets/42280186/a2541546-d27c-431f-8508-5c5857499349)

**Comment by Magnetrix** [comment]
[ESP32-SBC-FabGL_Rev_A.pdf](https://github.com/EremusOne/ZX-ESPectrum-IDF/files/11960133/ESP32-SBC-FabGL_Rev_A.pdf)

**Comment by EremusOne** [comment]
Hi again Magnetrix,

As I told you before, we own no Olimex board to work with and test the emu so we can't test any fix on it. We only release binaries for boards or products we have been able to test thoroughly. Right now, these are the Lilygo TTGO VGA32 and Antonio Villena's ESPectrum board. This may change in the future but can't give you an ETA.

This is done this way for a good reason: to reduce this kind of issues we are talking of right now. Bear in mind we work in this project in our spare time and have to be cautious with the compromises we assume.

Anyway, if u have managed to flash binaries on the board I'm sure you'll be able to install VSCode and PlatformIO, download the source, apply the suggested fix, compile it and flash to the board. It's easier than you may think.

Good luck and tyvm for your interest in ESPectrum!

P.S.: And don't forget to read the doc you sent before asking please: you have the answer for the buzzer issue right there (TIP: BUZ_EN1).
