### ISSUE TITLE
Selected z80 or TAP changed after loading

### ISSUE THREAD

**Issue by rcmolina** [EremusOne/ZX-ESPectrum-IDF#27]
Verification:
1) open z80 files with f2
2) position selected is first sorted z80 file
3) move dow to select a random z80 file
4) enter to load/execute
5) now reopen again z80 files with f2 to select another z80 file
6) position selected is again first z80 file, this should be done only after hard reset

**Comment by EremusOne** [comment]
Hi Rafa,

That was already on the TO DO list. Next public release (and Patreon prereleases) will have lots of file management improvements :)

Thanks anyway for your interest in our project!
