### ISSUE TITLE
Muted sound not recovered after loading new snapshot

### ISSUE THREAD

**Issue by rcmolina** [EremusOne/ZX-ESPectrum-IDF#31]
Hi Víctor,

Verify with this MOP:

1) Load Monty z80 from here
https://github.com/rcmolina/z802tzx3/blob/master/MONTY2.z80
2) Wait until game initial sound
3) Press F2 again and reopen the same file.
4) If sound still working, then repeat loading again.
5) If not sound any more, when F2 also notice  moving the selecting file bar does nor generate any tick,, sound is lost forever until reset with F12

**Comment by rcmolina** [comment]
Closed until more testing..

**Comment by EremusOne** [comment]
Hi!

This problem is now solved on release 1.0 :)

Tyvm for taking your time to test it
