### ISSUE TITLE
SD Card Support

### ISSUE THREAD

**Issue by AxelAhlborn** [EremusOne/ZX-ESPectrum-IDF#35]
Hi,
I assume that I can use a 32GB formatted FAT32 SD card. The directories documented under RC3 no longer seem to exist? I put everything in the root? I only created the two newly documented directories. Correct?
Greetings Axel

**Comment by EremusOne** [comment]
Hi Axel!

There should be no problem. I use a 32GB Sandisk Ultra card for development and it works like a charm.

It is correct: The only directories you need to create right now are .c for the screen captures and .p for persistent snapshots.

Happy new year and tyvm for your interest in ESPectrum ;)
