### ISSUE TITLE
POKE function Issue. 

### ISSUE THREAD

**Issue by Gods69** [EremusOne/ZX-ESPectrum-IDF#40]
Hi.
I see a new POKE function with "SS"+"CS"+"O" keys press.
When i go to the address box, i can delete the "16384" value with "CS" +"0" but i can't input a new value with the numeric keys 
on the Antonio Villena's ESPectrum board.
Thanks.

**Comment by EremusOne** [comment]
Hi!

Right now, with the ZX keyboard for entering letters or numbers inside input boxes at the ESPectrum interface (Search function on file dialogs, Address and value at poke dialog) you have to use Symbol Shift + letter or number.

Regards ;)
