### ISSUE TITLE
Update error.

### ISSUE THREAD

**Issue by Gods69** [EremusOne/ZX-ESPectrum-IDF#73]
Hi,
Can not update via SD card. Updating via the Update menu stop with an error code 260.
(using the firmware.upg file)

**Comment by EremusOne** [comment]
Hi,
Bear in mind that you only can update via SD if you are using some version 1.3 prerelease because partition scheme is different from version 1.2
So, if you come from 1.2 is better to flash the entire .bin image or use the web flashing tool.
Greetings!

**Comment by Gods69** [comment]
OK. I updated to v1.3 with the Espressif flash tool.
