### ISSUE TITLE
COVOX support

### ISSUE THREAD

**Issue by s-e-r-g** [EremusOne/ZX-ESPectrum-IDF#74]
Do we have COVOX support?
Covox is a 8bit DAC.
It has several versions:
Port #FB on Pentagon
 #DD on Scorpion
Stereo Covox: #3F and probably #5F on Profi.

It's just a port with attached DAC on it. We could add (if it's possible ) covox support for at least mono version.

**Comment by EremusOne** [comment]
Thanks for the tip. Covox through port 0xFB it's coming (yet working in test code) ;D
